// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAJo_4GqlfbpJAxu2quVTGI7VhxGJKt0',
    appId: '1:1090692087097:web:6961c146c60b757b4cbce8',
    messagingSenderId: '1090692087097',
    projectId: 'goal-d9310',
    authDomain: 'goal-d9310.firebaseapp.com',
    storageBucket: 'goal-d9310.firebasestorage.app',
    measurementId: 'G-P1JZE3PP2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArN43Hao7UZ13gibbPmc6VbryUJ-6qHng',
    appId: '1:1090692087097:android:c302ae62dc28c3444cbce8',
    messagingSenderId: '1090692087097',
    projectId: 'goal-d9310',
    storageBucket: 'goal-d9310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4MeCq_em8SUbhTrGP8IsrED4A24JTe5s',
    appId: '1:1090692087097:ios:39823707d55215734cbce8',
    messagingSenderId: '1090692087097',
    projectId: 'goal-d9310',
    storageBucket: 'goal-d9310.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4MeCq_em8SUbhTrGP8IsrED4A24JTe5s',
    appId: '1:1090692087097:ios:39823707d55215734cbce8',
    messagingSenderId: '1090692087097',
    projectId: 'goal-d9310',
    storageBucket: 'goal-d9310.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiAJo_4GqlfbpJAxu2quVTGI7VhxGJKt0',
    appId: '1:1090692087097:web:503a1994228a36ed4cbce8',
    messagingSenderId: '1090692087097',
    projectId: 'goal-d9310',
    authDomain: 'goal-d9310.firebaseapp.com',
    storageBucket: 'goal-d9310.firebasestorage.app',
    measurementId: 'G-9HEY48FKTY',
  );
}
